In [1]:


import numpy as np # linear algebra


In [2]:
array=np.array([5,6,9])

print(array)


[5 6 9]


In [3]:
arrayx= np.array([1,2,3,4,5,6,7,8,9])
print(arrayx.shape)

(9,)


In [4]:
c = arrayx.reshape(3,3) 
print(c)
print("shape: ",c.shape)

print("dimension: ",c.ndim) #matris boyutu

print("data type: ",c.dtype.name) 


print("size: ",c.size) #önceki boyutu
                       
print("type",type(c)) #type <class 'numpy.ndarray'>

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape:  (3, 3)
dimension:  2
data type:  int64
size:  9
type <class 'numpy.ndarray'>


In [5]:
a= np.array([[2,3,4],[6,7,8],[9,10,11]])  #reshape olmadan boyut değişikliği için
print(a)
print(a.shape)


[[ 2  3  4]
 [ 6  7  8]
 [ 9 10 11]]
(3, 3)


In [6]:
zeros= np.zeros((2,5))  #sıfırlardan oluşan array yaratır
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
ones=np.ones((2,2))       #birlerden oluşan matris yaratma
ones

array([[1., 1.],
       [1., 1.]])

In [8]:
np.empty((2,3))     #boş array


array([[4.65953277e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [9]:
z= np.linspace(1,100,10)  #1 ile 100 arasında 10 sayı yazdıracak
print(z)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [10]:
a= np.array([2,2,3])
b= np.array([5,7,9]) #toplama çıkarma gibi işlemlerde boyutlarının aynı olması önemlidir!!

print(a+b) 
print(a-b) 
print(a**2) 




[ 7  9 12]
[-3 -5 -6]
[4 4 9]


In [11]:
list = [1,2,3,4]
array = np.array([5,6,7,8]) #array tanımlamak için array'in içine liste yazılır.

print(list)
print(array)
array = np.array(list)
print(array)


[1, 2, 3, 4]
[5 6 7 8]
[1 2 3 4]


In [12]:
a = np.array([1,2])
print(a)
b=a

c=a

b[0]=4
print(a,b,c)     #a,b,c arraylerinin hepsinin 0. indeksi değişir. Bir tanesi değişince hepsi değişir.
d = a.copy()   #kopyalıyor. birinin indeksi değişince diğeri etkilenmemesi için.
d    

a= np.array([4,5,6,7])
print(a)
print(a[0])  #ilk eleman
print(a[1:3]) #1'den 3'e(dahil değil) indeks yazdıracak
reverse_array = a[::-1]        #array'i ters çevirir.!!
print(reverse_array)


[1 2]
[4 2] [4 2] [4 2]
[4 5 6 7]
4
[5 6]
[7 6 5 4]


In [13]:
x= np.array([[10,11,12,13],[9,8,7,6]]) 
print(x)

print(x[1,1]) #1.satır 1.sütun
print(x[:,1])  
print(x[1,:]) 
print(x[1,1:4]) 

print(x[-1,:])

print(x[:,-1]) 

[[10 11 12 13]
 [ 9  8  7  6]]
8
[11  8]
[9 8 7 6]
[8 7 6]
[9 8 7 6]
[13  6]


In [14]:
array = np.array([[1,2],[3,4],[5,6]]) 
print(array)
b = array.ravel() #ravel methoduyla tek boyutlu hale getirilir.!
print(b)
array_transpose = array  #transpose alınır.
print(array_transpose) #[[1 2]
                       #[3 4]
                       #[5 6]]


[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [15]:
arrayz=np.array([[2,3],[4,5],[6,7]])
print(arrayz)

[[2 3]
 [4 5]
 [6 7]]


In [16]:
#resize ile yapılan boyut değişimleri kalıcıdır, aynı array'in içine kaydeder.
#reshape ile yapılan değişimler kalıcı değildir. yapılan değişim başka bir değişkene kaydedilmelidir.
arrayz.resize(2,3)
print(arrayz)


[[2 3 4]
 [5 6 7]]
